export interface Part {
  id: string;
  Description: string;
  Usage: string;
  Discont: number,
  StartAmount: number;
  StartPrice: number;
  CostOfDelivery: number;
  TimeOfDelivery: number;
  DeviationOfDelivery: number;
  ProcessingTimeWS1: number;
  ProcessingTimeWS2: number;
  ProcessingTimeWS3: number;
  ProcessingTimeWS4: number;
  ProcessingTimeWS6: number;
  ProcessingTimeWS7: number;
  ProcessingTimeWS8: number;
  ProcessingTimeWS9: number;
  ProcessingTimeWS10: number;
  ProcessingTimeWS11: number;
  ProcessingTimeWS12: number;
  ProcessingTimeWS13: number;
  ProcessingTimeWS14: number;
  ProcessingTimeWS15: number;
  SetupTimeWS1: number;
  SetupTimeWS2: number;
  SetupTimeWS3: number;
  SetupTimeWS4: number;  
  SetupTimeWS6: number;
  SetupTimeWS7: number;
  SetupTimeWS8: number;
  SetupTimeWS9: number;
  SetupTimeWS10: number;
  SetupTimeWS11: number;
  SetupTimeWS12: number;
  SetupTimeWS13: number;
  SetupTimeWS14: number;
  SetupTimeWS15: number;
}